### PR TITLE
Backend on PHP.md file modified to sort warnings and an error

### PR DESCRIPTION
**Pull request by 8ivek**
If there are any queries about my changes please let me know.

### CODE REVIEW

**Comment by steffentchr** [comment]
Looks good in the PHP file, but any chance you can submit a pull request without the `dlfk` file? ;)

**Comment by 8ivek** [comment]
Ok :)

**Comment by 8ivek** [comment]
@steffentchr  Done :)

**Comment by 8ivek** [comment]
I am new to github contributing to repositories so please correct me If I have done anything wrong.

**Comment by steffentchr** [comment]
Beautitful, thanks man!

**Comment by 8ivek** [comment]
Cheers thank you steffentchr

**Comment by 8ivek** [comment]
:+1:  my email is: bivek_j AT yahoo.com and meetbivek AT gmail.com

**Pull request merged**
