### PR TITLE
[UPDATE] catch 409 in actual code

### PR DESCRIPTION
**Pull request by OzoTek**
Wooops, hi again,

It looks like I had updated the samples instead of the actual code... sorry for the inconvenience.

@steffentchr Could you have a look please? It's the same update as https://github.com/23/resumable.js/pull/431, except in the right folder 😅

### CODE REVIEW

**Comment by flmg** [comment]
Any news on this guys? I need this as well and it doesn't seem to be a hard merge ;)

**Comment by steffentchr** [comment]
Done -- sorry I missed this one in Dec.

**Comment by OzoTek** [comment]
Thanks! Could you publish it on NPM? :)

**Comment by steffentchr** [comment]
That's not as instant -- any reason for not just specifying the `409` in code?

**Comment by OzoTek** [comment]
Do you mean in my side?
I wanted to, but as 409 is not considered an error, it's entering the `fileProgress` event, and I can't seem to find the status code in the response, so I can't handle this myself. But maybe I missed something?
And from a conceptual POV, I think handling 409 as an error makes sense, and we let the user decide how we wants to handle it (override, cancel, add a suffix to the name...).

**Comment by steffentchr** [comment]
Was thinking more about something like this:

    var r = new Resumable({
      permanentErrors:[400, 404, 409, 415, 500, 501],
      ....
    });

This would have the same effect.

**Comment by OzoTek** [comment]
Yes indeed, I must have missed that one! Thanks.

**Pull request merged**
