### PR TITLE
fix uploading folder with more than 100 files within

### PR DESCRIPTION
**Pull request by Lehakos**
I got solution from here https://github.com/owncloud/core/issues/19834#issuecomment-204132460

### CODE REVIEW

**Comment by steffentchr** [comment]
Great addition, thanks!

**Comment by Lehakos** [comment]
@steffentchr Can we update version in package.json?

**Comment by Lehakos** [comment]
@bmaland @jamescarlos @2xyo @Mestika

**Comment by vicente-dl** [comment]
Hello I have been experiencing this issue, is this library is still being updated?

**Pull request merged**
