### PR TITLE
update minFileSize default

### PR DESCRIPTION
**Pull request by cooltoast**
minFileSize actually defaults to 1 byte, not undefined

### CODE REVIEW

**Comment by cooltoast** [comment]
@steffentchr is this PR good to go?

**Comment by steffentchr** [comment]
This is only for docs, or?

**Comment by cooltoast** [comment]
@steffentchr yes the docs do not have the proper value (https://github.com/23/resumable.js/blob/master/resumable.js#L79)

my application allowed for empty files and I was confused why errors were being thrown, until I realized I made an incorrect assumption from the docs after reading the code

**Comment by cooltoast** [comment]
hi @steffentchr can we merge this PR?

**Pull request closed without merging**
