### PR TITLE
Few improvements

### PR DESCRIPTION
**Pull request by adavidof**
Add `testTarget` as method to check if the chunk is already exists

@steffentchr

### CODE REVIEW

**Comment by steffentchr** [comment]
Hi @adavidof -- thanks for the contribution, it's much appreciated. `cb3926f` and `fee5902` are great, and I think the intention in `0139815` is good, happy to accept a contribution adding that feature. In the current form though, `testTarget` is set by default, which adds confusion and effectively mean that you won't be able to set the test target to `testTarget`. I suggest that the default is `null`, and then testing against that -- would that work for you?

Style changes such as `ff48aa7` and `205fc97` since they explicitly undo our own style guides, hope that makes sense.

**Comment by adavidof** [comment]
@steffentchr The test function will be invoke only if `testChunks` options is enabled.
So may be disable this option by default?

**Comment by steffentchr** [comment]
Just leave it as `null` in the PR and it should be alright ;)

**Comment by steffentchr** [comment]
Perfect, did you want to remove some of the styling commits -- or should I merge individual parts manually?

**Comment by adavidof** [comment]
ff48aa7 and 205fc97?
I can remove them from PR

**Comment by steffentchr** [comment]
Yup.

**Comment by adavidof** [comment]
@steffentchr was fixed, check please

**Comment by steffentchr** [comment]
Merged with thanks ;)

**Pull request merged**
