### PR TITLE
reset filequeue after processing

### PR DESCRIPTION
**Pull request by thewilli**
the file queue was not reseted after all queued files have been processed (even though there was a comment claminig it was done). this lead to unwanted side effects (wrong id generation and repeated uploads of already uploaded files).

### CODE REVIEW

**Comment by steffentchr** [comment]
Thanks for the contribution @thewilli. 

Is the `queueLength = 0;` correct? It seems that this variable should be in/decremented elsewhere.

**Comment by thewilli** [comment]
@steffentchr 

> Is the `queueLength = 0;` correct?

Imho it is. And here's why:

Files get into resumable.js by eitiher dropping or browsing. Both kinds are finally processed by `appendFilesFromFileList(fileList, event)`, which I've slightly modified in an earlier PR. As the *queue* part happens before, and files chosen in a file browse dialog (-> `$.assignBrowse()`) are directly passed to `appendFilesFromFileList` let's only concentrate on dropped files.

When files are dropped the `onDrop(event)` helper function is invoked which checks for the event type and then lets `loadFiles(items, event)` do the further work. Here is where some iteration occurs and for each dropped item the queue length is increased and the item is passed to `enqueueFileAdditon` ([here](https://github.com/23/resumable.js/blob/e932d21/resumable.js#L234) and [here](https://github.com/23/resumable.js/blob/e932d21/resumable.js#L241)).

There comes the relevant part for this PR

```js
if (queueFiles.length == queueLength) {
   appendFilesFromFileList(queueFiles, event);
}
```

We've added some files to the queue and now want to wait for the last (synchronous) `enqueueFileAddition` invocation, where the last item has been added to the queue. In this case we need to reset the queue, in order to not re-add the files again, whenever we drop files again.

```js
if (queueFiles.length == queueLength) {
  // process files
  appendFilesFromFileList(queueFiles, event);
  // flush the queue
  queueFiles = [];
  queueLength = 0;
}
```

So what happens if we omitted `queueLength = 0`? We would just never pass the condition `queueFiles.length == queueLength` again (can be easily tested).

>  It seems that this variable should be in/decremented elsewhere.

Well, I don't think this variable is needed at all (neither is the queue), as in all use cases the iteration occurs synchronously, by using some kind of e.g. `map`, but I didn't want to mess with the code style :wink: And why wouldn't you want to reset the length (count) of a queue together with its content?

hth, thewilli

**Comment by steffentchr** [comment]
Makes sense. 
I think you're right though that the variable should be removed entirely -- instead of staying around in a limbo state. Would you want to update the PR or should I go ahead and merge+augment?

**Comment by steffentchr** [comment]
Looks great -- will be able to run the manual merge some time later this week.

**Comment by steffentchr** [comment]
Hey -- that made it easier, thank you ;)

**Comment by thewilli** [comment]
you're welcome :wink:

**Pull request merged**
