### PR TITLE
Expose addFiles method

### PR DESCRIPTION
**Pull request by zzarcon**
I exposed a new public method **addFiles**. It works same as **addFile** but you can pass multiple files at once.

```javascript
const resumable = new Resumable();
const files = [new File([], 'test.tmp'), new File([], 'foo.bar')];

resumable.addFiles(files);
```

This is needed in the case that you want to receive consistent events for bulk file adding.

Let me know if I need to update any other file.

Thanks!

### CODE REVIEW

**Comment by zzarcon** [comment]
@steffentchr @cpnielsen any chance to have a look into this? :crossed_fingers:

**Comment by cpnielsen** [comment]
Simple, straightforward, looks good 👍  Thanks @zzarcon!

**Comment by zzarcon** [comment]
@cpnielsen awesome! thanks 🙌

**Comment by majames** [comment]
@cpnielsen when will this be released? which version for resumable.js will it go into?

**Comment by majames** [comment]
@cpnielsen could you please give us an update on this? really looking forward to the next release! 😄

**Comment by cpnielsen** [comment]
@majames We are looking to make a general resumable.js release this week (hopefully), likely bumping the version number to 1.1.0, but I cannot say exactly when this will happen.

**Pull request merged**
